### ISSUE TITLE
Add conda package

### ISSUE THREAD

**Issue by mhavu** [bfieldtools/bfieldtools#47]
It would be nice to have an official conda package for bfieldtools. I managed to build a conda package for bfieldtools using the following meta.yaml:

```yaml
{% set name = "bfieldtools" %}
{% set version = "0.9.13.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a3051d1df8a69dbfce27ddf6fad143a68ae8f5348ec6d07a7b57a92d704516ee

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - cvxopt
    - cvxpy >=1.1.14
    - matplotlib
    - mayavi
    - numpy
    - pip
    - psutil
    - pyqt >=5
    - pyqt5-sip
    - python
    - quadpy >=0.16
    - scipy
    - shapely
    - setuptools_scm
    - sip
    - trimesh
  run:
    - cvxopt
    - cvxpy >=1.1.14
    - matplotlib
    - mayavi
    - numpy
    - psutil
    - pyqt >=5
    - pyqt5-sip
    - python
    - quadpy >=0.16
    - scipy
    - shapely
    - sip
    - trimesh

test:
  imports:
    - bfieldtools
    - bfieldtools.legacy
    - tests
    - tests.test_examples

about:
  home: "https://bfieldtools.github.io/"
  license: "BSD (3-clause)"
  license_family: BSD
  license_file: 
  summary: "Open-source Python software for magnetic field modeling"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
```

(I did not require PyQt <5.15, as PyQt 5.15.7 installed on my system seemed to work just fine.)
